# Generated by Django 5.2.4 on 2025-08-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboissim', '0008_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='exterieurs',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='external_cvs/'),
        ),
        migrations.AddField(
            model_name='exterieurs',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='external_profiles/'),
        ),
    ]
