# Generated by Django 5.2.4 on 2025-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboissim', '0010_userprofile_is_team_lead_userprofile_role_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='projects', to='laboissim.projectdocument'),
        ),
    ]
